spring.application.name=project-demoday

# perfil padr�o
spring.profiles.active=dev

spring.config.import=optional:file:.env

# Liga as propriedades do Spring �s vari�veis lidas
openai.api.url=https://api.openai.com/v1/chat/completions
openai.api.key=${OPENAI_API_KEY}

# JWT Configuration
jwt.secret=sopro-chave-secreta-super-segura-256bits-minimo-aqui
jwt.expiration=86400000


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true