spring.application.name=project-demoday

# perfil padrão
spring.profiles.active=dev
# Força o Spring Boot a carregar o arquivo oculto .env na inicialização
spring.config.import=optional:file:.env

# Liga as propriedades do Spring às variáveis lidas do teu .env
openai.api.url=${OPENAI_API_URL}
openai.api.key=${OPENAI_API_KEY}