# Configuração para Desenvolvimento Local
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sopro_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:suasenha}

# Mantém o banco atualizado com as entidades JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true