spring.application.name=project-demoday

# Força a aplicação a usar sempre o perfil de desenvolvimento (MySQL)
spring.profiles.active=dev

# Permite ler as chaves de API e credenciais do ficheiro .env local
spring.config.import=optional:file:.env