# CONFIGURAÇÃO DE PRODUÇÃO - LÊ DIRETO DO PAINEL DA AZURE
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Dialeto correto para o Azure SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Chaves de API das Inteligências Artificiais
gemini.api.key=${GEMINI_API_KEY}
openai.api.key=${OPENAI_API_KEY}

# Configurações de Inicialização e Segurança
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

# JWT Security Config fixo para testes locais em prod funcionarem
jwt.secret=sopro-chave-secreta-super-segura-256bits-minimo-aqui
jwt.expiration=86400000