spring.datasource.url=postgresql://sopro_admin:x0hcLnsgjRzq0gcj141TZF0tZNf4Wt6C@dpg-d8itgmr7uimc73b5be90-a/sopro_db
spring.datasource.username=sopro_admin
spring.datasource.password=x0hcLnsgjRzq0gcj141TZF0tZNf4Wt6C

# Configurações que faltavam para o PostgreSQL funcionar na nuvem:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Impede que o data.sql rode em produção (evita duplicar dados no RAG a cada deploy)
spring.sql.init.mode=never